apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "daily-redirector.fullname" . }}
  labels:
    app: {{ template "daily-redirector.name" . }}
    chart: {{ template "daily-redirector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CACHE_SIZE: {{ .Values.appConfig.cacheSize | quote }}
  API_URL: {{ .Values.appConfig.apiUrl }}
  GCLOUD_PROJECT: {{ .Values.appConfig.gcloudProject }}

